/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/posts/1-mini-nest-js': RouteRecordInfo<'/posts/1-mini-nest-js', '/posts/1-mini-nest-js', Record<never, never>, Record<never, never>>,
    '/posts/2-component-maintainability': RouteRecordInfo<'/posts/2-component-maintainability', '/posts/2-component-maintainability', Record<never, never>, Record<never, never>>,
    '/posts/3-nest-prisma-aspect': RouteRecordInfo<'/posts/3-nest-prisma-aspect', '/posts/3-nest-prisma-aspect', Record<never, never>, Record<never, never>>,
    '/posts/4-dlight': RouteRecordInfo<'/posts/4-dlight', '/posts/4-dlight', Record<never, never>, Record<never, never>>,
    '/posts/5-rollup-config': RouteRecordInfo<'/posts/5-rollup-config', '/posts/5-rollup-config', Record<never, never>, Record<never, never>>,
    '/posts/6-vue-ts': RouteRecordInfo<'/posts/6-vue-ts', '/posts/6-vue-ts', Record<never, never>, Record<never, never>>,
    '/posts/7-auto-scan': RouteRecordInfo<'/posts/7-auto-scan', '/posts/7-auto-scan', Record<never, never>, Record<never, never>>,
    '/posts/8-apple-watch-2023': RouteRecordInfo<'/posts/8-apple-watch-2023', '/posts/8-apple-watch-2023', Record<never, never>, Record<never, never>>,
    '/posts/9-2024-first-half-trifles': RouteRecordInfo<'/posts/9-2024-first-half-trifles', '/posts/9-2024-first-half-trifles', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
  }
}
